osx-image: xcode9.2
language: objective-c

script:
 - xcodebuild test -workspace amaro.xcworkspace -scheme amaro -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.1' ONLY_ACTIVE_ARCH=NO | xcpretty 
